version: '3.7'

services:
  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=j9$$r@4)%#b*84eu%=nsehn9t@xk3ic4i_)mg_to!mf$$8b8%(87
  postgres:
    image: postgres:11.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django_db_user
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=django_db
volumes:
    postgres_data:
